php_packages:
  - php7.1-common
  - php7.1-cli
  - php7.1-fpm
  - php7.1-apcu
  - php7.1-curl
  - php7.1-gd
  - php7.1-intl
  - php7.1-json
  - php7.1-mbstring
  - php7.1-opcache
  - php7.1-sqlite3
  - php7.1-xml
  - php7.1-zip