---
- hosts: my_instance
  remote_user: ubuntu
  become: true
  gather_facts: false

  vars_prompt:
    - name: my_instance_ip
      prompt: "Enter IP address of your AWS instance"

  tasks:
    - name: Install Python
      raw: "apt-get update && apt-get -y -q install python"

- hosts: my_instance
  remote_user: ubuntu
  become: true
  gather_facts: true

  vars_prompt:
    - name: my_instance_ip
      prompt: "Enter IP address of your AWS instance"

  roles:
    - server
    - geerlingguy.nginx
    - geerlingguy.php
    - geerlingguy.composer